Watching for file changes with StatReloader
Not Found: /docs
"GET /docs HTTP/1.1" 404 2424
Index page accessed
Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 15, in main
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/main.html
"GET /main/ HTTP/1.1" 500 79719
Index page accessed
Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 15, in main
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/main.html
"GET /main/ HTTP/1.1" 500 79856
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 78871
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 78597
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2394
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 78871
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
"GET /static/admin/css/base.css HTTP/1.1" 200 21544
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 79472
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 79198
Index page accessed
Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 15, in main
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/main.html
"GET /main/ HTTP/1.1" 500 80594
Index page accessed
Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 15, in main
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/main.html
"GET /main/ HTTP/1.1" 500 80320
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2394
Not Found: /docs
"GET /docs HTTP/1.1" 404 2424
Index page accessed
"GET /main/ HTTP/1.1" 200 183
Index page accessed
"GET /main/ HTTP/1.1" 200 183
Index page accessed
"GET /about/ HTTP/1.1" 200 176
Index page accessed
"GET /about/ HTTP/1.1" 200 176
